### ISSUE TITLE
Custom Redis object/connection options

### ISSUE THREAD

**Issue by paulocheque** [agoragames/leaderboard-python#39]
It is possible to customize the `redis_connection`, but what about the `connection_pool`?

I would like to use the `decode_responses ` from `ConnectionPool` of **redis-py** option:

    redis.from_url(redis_url, decode_responses=True)

    Leaderboard('...', ?????)

    Leaderboard('...', redis_connection=redis.from_url(redis_url, decode_responses=True))????
    Leaderboard('...', connection=redis.from_url(redis_url, decode_responses=True))????

Should not be a good idea let the `decode_responses=True` as default in the leaderboard lib?

Thanks in advance.

**Comment by czarneckid** [comment]
@paulocheque Good idea. If you'd like to submit a PR with that functionality, please do.
