### ISSUE TITLE
How to rank based on criteria?

### ISSUE THREAD

**Issue by ShipraShalini** [agoragames/leaderboard-python#41]
I'm using leaderboard-python for creating leaderboard.
Global rank is coming out fine but I wish to rank users based on their country.
Do I have to create different leaderboard for each country or is there any filtering mechanism for this?

P.S. I have very little idea of Redis, so explanation with sample code would be very much appreciated.

**Comment by czarneckid** [comment]
Yes, you'll need to create separate leaderboards per country.
