### ISSUE TITLE
Sorting Competition Leaderboard by rank ( for a given set of users )

### ISSUE THREAD

**Issue by clevercricket** [agoragames/leaderboard-python#42]
For ranked_in_list API in CompetitionLeaderboard if any user id doesn't exist in a leaderboard and 'sort_by' = 'rank' is used, then the API throws an exception ( 'rank' key not found ). Whereas it works if the 'sort_by' = 'score' is used.

The bug is 'rank' is not initialised to None - unlike 'score' which by default is initialised to None.
This can be fixed with the following:

data[self.RANK_KEY] = None in line 100 or so as shown here:

            score = responses[index * 2 + 1]
            if score is not None:
                score = float(score)
            data[self.SCORE_KEY] = score

            data[self.RANK_KEY] = None # This is the additional line

            if self.order == self.ASC:
                data[self.RANK_KEY] = self.redis_connection.zcount(
                    leaderboard_name, '-inf', "(%s" % str(float(data[self.SCORE_KEY])))
            else:
                #print "SCORE_KEY - " + str(data[self.SCORE_KEY])
                if data[self.SCORE_KEY] != None:
                        data[self.RANK_KEY] = self.redis_connection.zcount(
                            leaderboard_name, "(%s" % str(float(data[self.SCORE_KEY])), '+inf')

**Comment by czarneckid** [comment]
What version of the library and Redis are you using? I cannot reproduce this locally using the latest leaderboard-python (3.5.0) and Redis (3.0.4). 

This test passes:

~~~python
    def test_ranked_in_list_does_not_throw_exception_for_user_not_in_list_when_sort_by_is_set_to_rank(self):
        self.__rank_members_in_leaderboard(26)

        leaders = self.leaderboard.ranked_in_list(
            ['member_1', 'member_15', 'member_25', 'member_200'], sort_by='rank')
        len(leaders).should.equal(4)
        leaders[0]['member'].should.equal('member_200')
        leaders[1]['member'].should.equal('member_25')
        leaders[2]['member'].should.equal('member_15')
        leaders[3]['member'].should.equal('member_1')
~~~

**Comment by clevercricket** [comment]
leaderboard-python is 3.1.0
redis 2.8.18
python 2.6

In my example, the only additional parameter i use is with_member_data = True

**Comment by czarneckid** [comment]
Looking at the history of the `CompetitionRankingLeaderboard` class, there's some exception handing in the call to Redis when trying to calculating the rank that was added in 3.3.0. You will need to upgrade to at least this version.

The error I was seeing running the tests under 3.1.0 was as follows:

```
======================================================================
ERROR: test_ranked_in_list_does_not_throw_exception_for_user_not_in_list_when_sort_by_is_set_to_rank (test.leaderboard.competition_ranking_leaderboard_test.CompetitionRankingLeaderboardTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dczarnecki/projects/leaderboard-python/test/leaderboard/competition_ranking_leaderboard_test.py", line 103, in test_ranked_in_list_does_not_throw_exception_for_user_not_in_list_when_sort_by_is_set_to_rank
    ['member_1', 'member_15', 'member_25', 'member_200'], sort_by='rank')
  File "/Users/dczarnecki/projects/leaderboard-python/leaderboard/leaderboard.py", line 948, in ranked_in_list
    self.leaderboard_name, members, **options)
  File "/Users/dczarnecki/projects/leaderboard-python/leaderboard/competition_ranking_leaderboard.py", line 107, in ranked_in_list_in
    leaderboard_name, "(%s" % str(float(data[self.SCORE_KEY])), '+inf')
TypeError: float() argument must be a string or a number
```

**Comment by clevercricket** [comment]
Thanks for the response. I updated the package to the latest version and the issue was resolved.
