### ISSUE TITLE
around_me_in does't work right on python 3.4 

### ISSUE THREAD

**Issue by jenyacazacu** [agoragames/leaderboard-python#49]
When using python 3.4 and requesting a leaderboard with a page_size=1 it returns the incorrect member due to the way python 3 handles division on **line 1007 in leaderboard/leaderboard.py**. The work around was to cast to int, so that fixed it for any page size.

starting_offset = reverse_rank_for_member - **(page_size / 2)**

should be 

starting_offset = reverse_rank_for_member - **int(page_size / 2)**

**Comment by GraylinKim** [comment]
Thanks for reporting this issue. I've added a test and submitted a patch.

**Comment by jenyacazacu** [comment]
awesome, thx
